#!/bin/sh

export PATH=/bin

echo "[nullroot-init] starting"

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "[nullroot-init] mounted pseudo-filesystems"

exec sh